version: '3'
services:
  web:
    image: praqma/network-multitool
    networks:
      - frontend
    command: tail -f /dev/null
  app:
    image: praqma/network-multitool
    networks:
      - frontend
      - backend
    command: tail -f /dev/null
  db:
    image: praqma/network-multitool
    networks:
      - backend
    command: tail -f /dev/null
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

